### ISSUE TITLE
Upper bounds don't work on python_requires

### ISSUE THREAD

**Issue by zooba** [microsoft/python-package-template#15]
https://github.com/microsoft/python-package-template/blob/1fb2c18490a0fdd5c2bbf0f6bc56846c48a480d5/setup.py#L61

Full discussion at https://discuss.python.org/t/requires-python-upper-limits/12663, but basically it was added to provide a programmatic way to let pip find earlier versions of a package to support earlier versions of Python. Older versions of a package generally can't support newer versions of Python than the newest package, so an upper bound isn't even checked.

**Comment by dciborow** [comment]
Will address this as I update from setup.py to pyproject.toml.
